### ISSUE TITLE
Fixes for preplaced platoon/Mission.sqm

### ISSUE THREAD

**Issue by Poulern** [ferstaberinde/F3#573]
Hey guys, i love the pre placed platoon, however i have some improvements that I've noticed.

1. The Squad Leaders for AAF are recruits instead of sergeants, ditto for CO and XO. 
2. If you could move the whole platoon down to the bottom left of the map, whenever you use it on a smaller map like stratis or a custom map you won't have to do an extra step with naming the folder, dragging it down to the bottom left, rename the folder and open it again. It's not something you open up in the editor anyways.
3. For FIA, maybe adding a mounted technical group? Seems odd that they don't have one.

Mostly issue nr.2 though. I can see why you have done it the way you have with altis being by default set to the AAC airfield, but i personally would prefer it being in the bottom left.

**Comment by Wolfenswan** [comment]
Good call about 2.

I remember moving them to where they are atm. exactly because they wouldn't appear properly on Stratis but haven't tested that with other maps.

About 1. is something that we barely notice in-game but I know that some groups put more importance in it. Not sure if I'll find the time to go through all units to set the proper ranks but making SLs/COs sergeants is quickly done.

3. I'll keep in mind, don't recall the argument on why or why not to add them when we first did their ORBAT. FIA does have the same pre-implemented group-markers as the other groups (IFV1 etc.).

**Comment by ferstaberinde** [comment]
I'll take this on.

**Comment by Wolfenswan** [comment]
Closing this one as it has been merged into dev.
