### ISSUE TITLE
Small bugs with latest version of spectator script

### ISSUE THREAD

**Issue by cptnnick** [ferstaberinde/F3#618]
Seems currently the spectator script has a few small issues when you JIP in:

* I had a wierd issue where the top bar started at the old position at the border of the screen and on hover over would move down, creating a gap between the top of the screen and the top of the bar.

* ACRE would refuse to connect when JIPping in.

**Comment by Sniperhid** [comment]
There were also some issues with reopening the spectator (gonna hijack this). Will attempt to test on FA and 1Tac servers.

To Test:
- [ ] Able to reopen spectator interface
- [ ] previous body of spectator disappears of disconnect

**Comment by Wolfenswan** [comment]
Will be tested with RC2.

**Comment by Cyruz143** [comment]
Adding a comment here rather than starting a new issue, Wolfy feel free to shout at me on Skype for being lazy.

There seems to be a bit of an issue with the distance sound envelope, if you're spectating a unit in third person the audible sounds of vehicles seems to get no attenuation effects meaning it's really loud compared to everything else.

If you zoom away from the spec target at around 400/500m you get an instant, very muffled vehicle sound (no gradual volume effects, just on/off like a switch). Move 50m more and it's silent completely.

This seems to be all vehicles, even a boat floating in the water playing it's ambient sound was very loud!

**Comment by Wolfenswan** [comment]
@Cyruz143 does the issues persist with RC2?

Someone reported not being able to open the chatbox from spectator. Not sure how this could be caused.
