### ISSUE TITLE
APEX assignGear & ORBAT considerations

### ISSUE THREAD

**Issue by Wolfenswan** [ferstaberinde/F3#706]
**Loadouts & Fatigue**
The loadouts are balanced for an older version of the fatigue/stamina system. A refactoring with slightly less load per unit might be appropriate. RATs (and ARs to a lesser degree) are probably fucked either way.

**FIA & Syndicate**
Syndicate seem to take FIAs role in Tanoa but are independent. Should FIA remain as a faction of their own or should they be merged into a single "Insurgent" assignGear (& Orbat?)

**Camo**
Apex adds new pacific camo for both major factions. These could either be added as commented lines in the gear files themselves or as an additional .sqf (e.g. assignGear_nato_pacific.sqf). Given the amount of camo gear (basically all existing gear gets a do-over) I think the latter is more appropriate.

**CTRG**
FA Template already adds their own assignGear file (and adds them to the FIA orbat). I'd add the assignGear file but not add them to the FIA ORBAT for 3-4-0.

**Viper**
Apex adds a new special-SPECIAL forces to CSAT, named Viper (similar to CTRG as a special NATO team). Should they get their own assignGear file? They boost some super high tech equipment mostly. Probably not worth an ORBAT of their own.

**Addition of new gear into old assignGear**
Should FIA get a weapons downgrade etc.

**Comment by ferstaberinde** [comment]
@Wolfenswan - Before we do any of this, IIRC I need to merge the FaxOrbat 2015 into the Dev branch (and the current FA template assignGear files).

**Comment by ninjaProtocol** [comment]
**Re: Loadouts & Fatigue**
Light/Medium loadouts seem to be fine, the heavy ones probably need to be tweaked (removed, perhaps?). I can remember at least one instance of spawning as an AR with so much stuff that my stamina was depleted from the start, and refused to regenerate.

**FIA & Syndicate**
I think keeping FIA as a separate vanilla faction is a better idea. Different camo, different languages, etc. Syndikat is also slightly weird as Bandit and Paramilitary are all under the same faction and have similar gear, but different uniforms. Then of course, those without Apex will start seeing ads if there's just a common Insurgent faction with mixed gear. Probably could just do FIA and Syndikat, with paramilitary as default but bandit uniforms commented out.

**Camo**
Indeed, separate `faction_pacific` loadout would seem more appropriate. What about CSAT, though? Would CSAT Urban get a separate file too,now?

**CTRG**
Agreed, but continuing from the "Camo" discussion, they probably need `ctrg_pacific` since the new uniforms don't have flags and have different helmets.

**Viper**
Again, agreed - like CTRG, can't see much use for a Viper ORBAT.

**Addition of new gear into old assignGear**
Probably not, because ads, maybe even backwards compatibility. I'd love FIA to have RPGs though! Maybe a `fia_alt` loadout could be used?

**Comment by ferstaberinde** [comment]
Just FYI, OrBat-meister comrade Ferrard Carson is working on this issue now. Watch this space.

**Comment by Ferrard** [comment]
For those interested in viewing the progress of our draft F3.4.0 loadouts, visit [this Google Sheets](https://docs.google.com/spreadsheets/d/1kIeh7w2e3UXJEa49wQIOw--bflZhU5Ny3nGo5mXTOYA/edit#gid=905640684).

Per Discord discussions, I have reduced weight somewhat from F3.3.0's "Medium" loadout and renamed the weight class "Standard." "Heavy" weight class has been eliminated outright. "Light" weight class has been retained as a no-armor, low-ammo option for short, low-intensity, or maneuver-focused missions. Non-Tanoa factions are not equipped with Tanoa-specific equipment.

Drafting continues - editing of assignGear scripts will occur at the end of the drafting process.

Comments welcome here or in the F3 Discord channel.

**Current status:**
- Fireteam, SL and CO loadouts completed
- Some Attachment loadouts completed
